### ISSUE TITLE
Build and Evil counters have distorted graphics

### ISSUE THREAD

**Issue by keltoff** [Lycowolf/streaming_deckbuilder#9]
![image](https://user-images.githubusercontent.com/12376064/74612744-84ee0100-5108-11ea-9964-b556955d1b03.png)
![image](https://user-images.githubusercontent.com/12376064/74612748-8b7c7880-5108-11ea-8fbe-c2486255d16f.png)
![image](https://user-images.githubusercontent.com/12376064/74612752-90412c80-5108-11ea-9fec-2fb360371416.png)

When buying cards, captions Build and Evil are moving a few pixels left and right and the letters are broken from time to time.
Zuzka

**Comment by Lycowolf** [comment]
This is caused by a code that centers the text: we calculate its width and height and divide by two. When the text has the right (wrong) dimensions, it gets placed at half-pixel boundary, which messes up the text antialiasing.

Pull request created.

**Comment by keltoff** [comment]
Still (again?) not completely solved.
The "Build" label consistently rendered glitched, probably again by antialiasing fail.

Possibly got broken with change of Globals from string labeling to enum (and string rendering related to that)

**Comment by Lycowolf** [comment]
Because you mention Globals converted to enum, I presume you see this error happens on refactor_loading branch. This branch is based on 2876789ba59e5671c8a6768f08d163ebc4a9989d that doesn't contain fixes from PR #10. I recommend rebasing onto current master :)
